# Generated by Django 5.2.15 on 2026-07-05 14:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_shout'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInstall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
